import chroma from "chroma-js";

/**
 * Represents the JSON scheme of a VS Code theme
 */
export interface Theme {
	$schema: "vscode://schemas/color-theme";
	type: ThemeType;
	name: string;
	colors: ThemeColors;
	tokenColors: ReadonlyArray<TokenColor>;
	semanticHighlighting: boolean;
	semanticTokenColors?: SemanticTokenColors;
}

export type ThemeType = "light" | "dark";

export type ThemeColors = {
	[T in ThemeColor]?: chroma.Color;
};

/**
 * All theme colors customizable in VS Code
 * Reference: https://code.visualstudio.com/api/references/theme-color
 */
type ThemeColor =
	// Contrast colors
	| "contrastActiveBorder"
	| "contrastBorder"
	// Base colors
	| "focusBorder"
	| "foreground"
	| "disabledForeground"
	| "widget.border"
	| "widget.shadow"
	| "selection.background"
	| "descriptionForeground"
	| "errorForeground"
	| "icon.foreground"
	| "sash.hoverBorder"
	// Window border
	| "window.activeBorder"
	| "window.inactiveBorder"
	// Text colors
	| "textBlockQuote.background"
	| "textBlockQuote.border"
	| "textCodeBlock.background"
	| "textLink.activeForeground"
	| "textLink.foreground"
	| "textPreformat.foreground"
	| "textSeparator.foreground"
	// Action colors
	| "toolbar.hoverBackground"
	| "toolbar.hoverOutline"
	| "toolbar.activeBackground"
	// Button control
	| "button.background"
	| "button.foreground"
	| "button.border"
	| "button.separator"
	| "button.hoverBackground"
	| "button.secondaryForeground"
	| "button.secondaryBackground"
	| "button.secondaryHoverBackground"
	| "checkbox.background"
	| "checkbox.foreground"
	| "checkbox.border"
	| "checkbox.selectBackground"
	| "checkbox.selectBorder"
	// Dropdown control
	| "dropdown.background"
	| "dropdown.listBackground"
	| "dropdown.border"
	| "dropdown.foreground"
	// Input control
	| "input.background"
	| "input.border"
	| "input.foreground"
	| "input.placeholderForeground"
	| "inputOption.activeBackground"
	| "inputOption.activeBorder"
	| "inputOption.activeForeground"
	| "inputOption.hoverBackground"
	| "inputValidation.errorBackground"
	| "inputValidation.errorForeground"
	| "inputValidation.errorBorder"
	| "inputValidation.infoBackground"
	| "inputValidation.infoForeground"
	| "inputValidation.infoBorder"
	| "inputValidation.warningBackground"
	| "inputValidation.warningForeground"
	| "inputValidation.warningBorder"
	// Scrollbar control
	| "scrollbar.shadow"
	| "scrollbarSlider.activeBackground"
	| "scrollbarSlider.background"
	| "scrollbarSlider.hoverBackground"
	// Badge
	| "badge.foreground"
	| "badge.background"
	// Progress bar
	| "progressBar.background"
	// Lists and trees
	| "list.activeSelectionBackground"
	| "list.activeSelectionForeground"
	| "list.activeSelectionIconForeground"
	| "list.dropBackground"
	| "list.focusBackground"
	| "list.focusForeground"
	| "list.focusHighlightForeground"
	| "list.focusOutline"
	| "list.focusAndSelectionOutline"
	| "list.highlightForeground"
	| "list.hoverBackground"
	| "list.hoverForeground"
	| "list.inactiveSelectionBackground"
	| "list.inactiveSelectionForeground"
	| "list.inactiveSelectionIconForeground"
	| "list.inactiveFocusBackground"
	| "list.inactiveFocusOutline"
	| "list.invalidItemForeground"
	| "list.errorForeground"
	| "list.warningForeground"
	| "listFilterWidget.background"
	| "listFilterWidget.outline"
	| "listFilterWidget.noMatchesOutline"
	| "listFilterWidget.shadow"
	| "list.filterMatchBackground"
	| "list.filterMatchBorder"
	| "list.deemphasizedForeground"
	| "tree.indentGuidesStroke"
	| "tree.inactiveIndentGuidesStroke"
	| "tree.tableColumnsBorder"
	| "tree.tableOddRowsBackground"
	// Activity bar
	| "activityBar.background"
	| "activityBar.dropBorder"
	| "activityBar.foreground"
	| "activityBar.inactiveForeground"
	| "activityBar.border"
	| "activityBarBadge.background"
	| "activityBarBadge.foreground"
	| "activityBar.activeBorder"
	| "activityBar.activeBackground"
	| "activityBar.activeFocusBorder"
	// Profiles
	| "profileBadge.background"
	| "profileBadge.foreground"
	// Side bar
	| "sideBar.background"
	| "sideBar.foreground"
	| "sideBar.border"
	| "sideBar.dropBackground"
	| "sideBarTitle.foreground"
	| "sideBarSectionHeader.background"
	| "sideBarSectionHeader.foreground"
	| "sideBarSectionHeader.border"
	// Minimap
	| "minimap.findMatchHighlight"
	| "minimap.selectionHighlight"
	| "minimap.errorHighlight"
	| "minimap.warningHighlight"
	| "minimap.background"
	| "minimap.selectionOccurrenceHighlight"
	| "minimap.foregroundOpacity"
	| "minimapSlider.background"
	| "minimapSlider.hoverBackground"
	| "minimapSlider.activeBackground"
	| "minimapGutter.addedBackground"
	| "minimapGutter.modifiedBackground"
	| "minimapGutter.deletedBackground"
	// Editor groups & tabs
	| "editorGroup.border"
	| "editorGroup.dropBackground"
	| "editorGroupHeader.noTabsBackground"
	| "editorGroupHeader.tabsBackground"
	| "editorGroupHeader.tabsBorder"
	| "editorGroupHeader.border"
	| "editorGroup.emptyBackground"
	| "editorGroup.focusedEmptyBorder"
	| "editorGroup.dropIntoPromptForeground"
	| "editorGroup.dropIntoPromptBackground"
	| "editorGroup.dropIntoPromptBorder"
	| "tab.activeBackground"
	| "tab.unfocusedActiveBackground"
	| "tab.activeForeground"
	| "tab.border"
	| "tab.activeBorder"
	| "tab.unfocusedActiveBorder"
	| "tab.activeBorderTop"
	| "tab.unfocusedActiveBorderTop"
	| "tab.lastPinnedBorder"
	| "tab.inactiveBackground"
	| "tab.unfocusedInactiveBackground"
	| "tab.inactiveForeground"
	| "tab.unfocusedActiveForeground"
	| "tab.unfocusedInactiveForeground"
	| "tab.hoverBackground"
	| "tab.unfocusedHoverBackground"
	| "tab.hoverForeground"
	| "tab.unfocusedHoverForeground"
	| "tab.hoverBorder"
	| "tab.unfocusedHoverBorder"
	| "tab.activeModifiedBorder"
	| "tab.inactiveModifiedBorder"
	| "tab.unfocusedActiveModifiedBorder"
	| "tab.unfocusedInactiveModifiedBorder"
	| "editorPane.background"
	| "sideBySideEditor.horizontalBorder"
	| "sideBySideEditor.verticalBorder"
	// Editor colors
	| "editor.background"
	| "editor.foreground"
	| "editorLineNumber.foreground"
	| "editorLineNumber.activeForeground"
	| "editorLineNumber.dimmedForeground"
	| "editorCursor.background"
	| "editorCursor.foreground"
	| "editor.selectionBackground"
	| "editor.selectionForeground"
	| "editor.inactiveSelectionBackground"
	| "editor.selectionHighlightBackground"
	| "editor.selectionHighlightBorder"
	| "editor.wordHighlightBackground"
	| "editor.wordHighlightBorder"
	| "editor.wordHighlightStrongBackground"
	| "editor.wordHighlightStrongBorder"
	| "editor.wordHighlightTextBackground"
	| "editor.wordHighlightTextBorder"
	| "editor.findMatchBackground"
	| "editor.findMatchHighlightBackground"
	| "editor.findRangeHighlightBackground"
	| "editor.findMatchBorder"
	| "editor.findMatchHighlightBorder"
	| "editor.findRangeHighlightBorder"
	| "search.resultsInfoForeground"
	| "searchEditor.findMatchBackground"
	| "searchEditor.findMatchBorder"
	| "searchEditor.textInputBorder"
	| "editor.hoverHighlightBackground"
	| "editor.lineHighlightBackground"
	| "editor.lineHighlightBorder"
	| "editorUnicodeHighlight.border"
	| "editorUnicodeHighlight.background"
	| "editorLink.activeForeground"
	| "editor.rangeHighlightBackground"
	| "editor.rangeHighlightBorder"
	| "editor.symbolHighlightBackground"
	| "editor.symbolHighlightBorder"
	| "editorWhitespace.foreground"
	| "editorIndentGuide.background"
	| "editorIndentGuide.activeBackground"
	| "editorInlayHint.background"
	| "editorInlayHint.foreground"
	| "editorInlayHint.typeForeground"
	| "editorInlayHint.typeBackground"
	| "editorInlayHint.parameterForeground"
	| "editorInlayHint.parameterBackground"
	| "editorRuler.foreground"
	| "editor.linkedEditingBackground"
	| "editorCodeLens.foreground"
	| "editorLightBulb.foreground"
	| "editorLightBulbAutoFix.foreground"
	| "editorBracketMatch.background"
	| "editorBracketMatch.border"
	| "editorBracketHighlight.foreground1"
	| "editorBracketHighlight.foreground2"
	| "editorBracketHighlight.foreground3"
	| "editorBracketHighlight.foreground4"
	| "editorBracketHighlight.foreground5"
	| "editorBracketHighlight.foreground6"
	| "editorBracketHighlight.unexpectedBracket.foreground"
	| "editorBracketPairGuide.activeBackground1"
	| "editorBracketPairGuide.activeBackground2"
	| "editorBracketPairGuide.activeBackground3"
	| "editorBracketPairGuide.activeBackground4"
	| "editorBracketPairGuide.activeBackground5"
	| "editorBracketPairGuide.activeBackground6"
	| "editorBracketPairGuide.background1"
	| "editorBracketPairGuide.background2"
	| "editorBracketPairGuide.background3"
	| "editorBracketPairGuide.background4"
	| "editorBracketPairGuide.background5"
	| "editorBracketPairGuide.background6"
	| "editor.foldBackground"
	| "editorOverviewRuler.background"
	| "editorOverviewRuler.border"
	| "editorOverviewRuler.findMatchForeground"
	| "editorOverviewRuler.rangeHighlightForeground"
	| "editorOverviewRuler.selectionHighlightForeground"
	| "editorOverviewRuler.wordHighlightForeground"
	| "editorOverviewRuler.wordHighlightStrongForeground"
	| "editorOverviewRuler.wordHighlightTextForeground"
	| "editorOverviewRuler.modifiedForeground"
	| "editorOverviewRuler.addedForeground"
	| "editorOverviewRuler.deletedForeground"
	| "editorOverviewRuler.errorForeground"
	| "editorOverviewRuler.warningForeground"
	| "editorOverviewRuler.infoForeground"
	| "editorOverviewRuler.bracketMatchForeground"
	| "editorError.foreground"
	| "editorError.border"
	| "editorError.background"
	| "editorWarning.foreground"
	| "editorWarning.border"
	| "editorWarning.background"
	| "editorInfo.foreground"
	| "editorInfo.border"
	| "editorInfo.background"
	| "editorHint.foreground"
	| "editorHint.border"
	| "problemsErrorIcon.foreground"
	| "problemsWarningIcon.foreground"
	| "problemsInfoIcon.foreground"
	| "editorUnnecessaryCode.border"
	| "editorUnnecessaryCode.opacity"
	| "editorGutter.background"
	| "editorGutter.modifiedBackground"
	| "editorGutter.addedBackground"
	| "editorGutter.deletedBackground"
	| "editorGutter.commentRangeForeground"
	| "editorGutter.commentGlyphForeground"
	| "editorGutter.commentUnresolvedGlyphForeground"
	| "editorGutter.foldingControlForeground"
	| "editorCommentsWidget.resolvedBorder"
	| "editorCommentsWidget.unresolvedBorder"
	| "editorCommentsWidget.rangeBackground"
	| "editorCommentsWidget.rangeBorder"
	| "editorCommentsWidget.rangeActiveBackground"
	| "editorCommentsWidget.rangeActiveBorder"
	// Diff editor colors
	| "diffEditor.insertedTextBackground"
	| "diffEditor.insertedTextBorder"
	| "diffEditor.removedTextBackground"
	| "diffEditor.removedTextBorder"
	| "diffEditor.border"
	| "diffEditor.diagonalFill"
	| "diffEditor.insertedLineBackground"
	| "diffEditor.removedLineBackground"
	| "diffEditorGutter.insertedLineBackground"
	| "diffEditorGutter.removedLineBackground"
	| "diffEditorOverview.insertedForeground"
	| "diffEditorOverview.removedForeground"
	| "diffEditor.unchangedRegionBackground"
	| "diffEditor.unchangedRegionForeground"
	| "diffEditor.unchangedCodeBackground"
	| "diffEditor.move.border"
	// Chat colors
	| "chat.requestBackground"
	| "chat.requestBorder"
	// Inline chat colors
	| "inlineChat.background"
	| "inlineChat.border"
	| "inlineChat.shadow"
	| "inlineChat.regionHighlight"
	| "inlineChatInput.border"
	| "inlineChatInput.focusBorder"
	| "inlineChatInput.placeholderForeground"
	| "inlineChatInput.background"
	| "inlineChatDiff.inserted"
	| "inlineChatrDiff.removed"
	// Editor widget colors
	| "editorWidget.foreground"
	| "editorWidget.background"
	| "editorWidget.border"
	| "editorWidget.resizeBorder"
	| "editorSuggestWidget.background"
	| "editorSuggestWidget.border"
	| "editorSuggestWidget.foreground"
	| "editorSuggestWidget.focusHighlightForeground"
	| "editorSuggestWidget.highlightForeground"
	| "editorSuggestWidget.selectedBackground"
	| "editorSuggestWidget.selectedForeground"
	| "editorSuggestWidget.selectedIconForeground"
	| "editorSuggestWidgetStatus.foreground"
	| "editorHoverWidget.foreground"
	| "editorHoverWidget.background"
	| "editorHoverWidget.border"
	| "editorHoverWidget.highlightForeground"
	| "editorHoverWidget.statusBarBackground"
	| "editorGhostText.border"
	| "editorGhostText.background"
	| "editorGhostText.foreground"
	| "editorStickyScroll.background"
	| "editorStickyScrollHover.background"
	| "debugExceptionWidget.background"
	| "debugExceptionWidget.border"
	| "editorMarkerNavigation.background"
	| "editorMarkerNavigationError.background"
	| "editorMarkerNavigationWarning.background"
	| "editorMarkerNavigationInfo.background"
	| "editorMarkerNavigationError.headerBackground"
	| "editorMarkerNavigationWarning.headerBackground"
	| "editorMarkerNavigationInfo.headerBackground"
	// Peek view colors
	| "peekView.border"
	| "peekViewEditor.background"
	| "peekViewEditorGutter.background"
	| "peekViewEditor.matchHighlightBackground"
	| "peekViewEditor.matchHighlightBorder"
	| "peekViewResult.background"
	| "peekViewResult.fileForeground"
	| "peekViewResult.lineForeground"
	| "peekViewResult.matchHighlightBackground"
	| "peekViewResult.selectionBackground"
	| "peekViewResult.selectionForeground"
	| "peekViewTitle.background"
	| "peekViewTitleDescription.foreground"
	| "peekViewTitleLabel.foreground"
	| "peekViewEditorStickyScroll.background"
	// Merge conflicts colors
	| "merge.currentHeaderBackground"
	| "merge.currentContentBackground"
	| "merge.incomingHeaderBackground"
	| "merge.incomingContentBackground"
	| "merge.border"
	| "merge.commonContentBackground"
	| "merge.commonHeaderBackground"
	| "editorOverviewRuler.currentContentForeground"
	| "editorOverviewRuler.incomingContentForeground"
	| "editorOverviewRuler.commonContentForeground"
	| "editorOverviewRuler.commentForeground"
	| "editorOverviewRuler.commentUnresolvedForeground"
	| "mergeEditor.change.background"
	| "mergeEditor.change.word.background"
	| "mergeEditor.conflict.unhandledUnfocused.border"
	| "mergeEditor.conflict.unhandledFocused.border"
	| "mergeEditor.conflict.handledUnfocused.border"
	| "mergeEditor.conflict.handledFocused.border"
	| "mergeEditor.conflict.handled.minimapOverViewRuler"
	| "mergeEditor.conflict.unhandled.minimapOverViewRuler"
	| "mergeEditor.conflictingLines.background"
	| "mergeEditor.changeBase.background"
	| "mergeEditor.changeBase.word.background"
	| "mergeEditor.conflict.input1.background"
	| "mergeEditor.conflict.input2.background"
	// Panel colors
	| "panel.background"
	| "panel.border"
	| "panel.dropBorder"
	| "panelTitle.activeBorder"
	| "panelTitle.activeForeground"
	| "panelTitle.inactiveForeground"
	| "panelInput.border"
	| "panelSection.border"
	| "panelSection.dropBackground"
	| "panelSectionHeader.background"
	| "panelSectionHeader.foreground"
	| "panelSectionHeader.border"
	// Status bar colors
	| "statusBar.background"
	| "statusBar.foreground"
	| "statusBar.border"
	| "statusBar.debuggingBackground"
	| "statusBar.debuggingForeground"
	| "statusBar.debuggingBorder"
	| "statusBar.noFolderForeground"
	| "statusBar.noFolderBackground"
	| "statusBar.noFolderBorder"
	| "statusBarItem.activeBackground"
	| "statusBarItem.hoverBackground"
	| "statusBarItem.prominentForeground"
	| "statusBarItem.prominentBackground"
	| "statusBarItem.prominentHoverBackground"
	| "statusBarItem.remoteBackground"
	| "statusBarItem.remoteForeground"
	| "statusBarItem.errorBackground"
	| "statusBarItem.errorForeground"
	| "statusBarItem.warningBackground"
	| "statusBarItem.warningForeground"
	| "statusBarItem.compactHoverBackground"
	| "statusBarItem.focusBorder"
	| "statusBar.focusBorder"
	| "statusBar.offlineBackground"
	| "statusBar.offlineForeground"
	// Title bar colors
	| "titleBar.activeBackground"
	| "titleBar.activeForeground"
	| "titleBar.inactiveBackground"
	| "titleBar.inactiveForeground"
	| "titleBar.border"
	// Menu bar colors
	| "menubar.selectionForeground"
	| "menubar.selectionBackground"
	| "menubar.selectionBorder"
	| "menu.foreground"
	| "menu.background"
	| "menu.selectionForeground"
	| "menu.selectionBackground"
	| "menu.selectionBorder"
	| "menu.separatorBackground"
	| "menu.border"
	// Command center colors
	| "commandCenter.foreground"
	| "commandCenter.activeForeground"
	| "commandCenter.background"
	| "commandCenter.activeBackground"
	| "commandCenter.border"
	| "commandCenter.inactiveForeground"
	| "commandCenter.inactiveBorder"
	| "commandCenter.activeBorder"
	// Notification colors
	| "notificationCenter.border"
	| "notificationCenterHeader.foreground"
	| "notificationCenterHeader.background"
	| "notificationToast.border"
	| "notifications.foreground"
	| "notifications.background"
	| "notifications.border"
	| "notificationLink.foreground"
	| "notificationsErrorIcon.foreground"
	| "notificationsWarningIcon.foreground"
	| "notificationsInfoIcon.foreground"
	// Banner colors
	| "banner.background"
	| "banner.foreground"
	| "banner.iconForeground"
	// Extension colors
	| "extensionButton.prominentForeground"
	| "extensionButton.prominentBackground"
	| "extensionButton.prominentHoverBackground"
	| "extensionButton.background"
	| "extensionButton.foreground"
	| "extensionButton.hoverBackground"
	| "extensionButton.separator"
	| "extensionBadge.remoteBackground"
	| "extensionBadge.remoteForeground"
	| "extensionIcon.starForeground"
	| "extensionIcon.verifiedForeground"
	| "extensionIcon.preReleaseForeground"
	| "extensionIcon.sponsorForeground"
	// Quick picker colors
	| "pickerGroup.border"
	| "pickerGroup.foreground"
	| "quickInput.background"
	| "quickInput.foreground"
	| "quickInputList.focusBackground"
	| "quickInputList.focusForeground"
	| "quickInputList.focusIconForeground"
	| "quickInputTitle.background"
	// Keybinding label colors
	| "keybindingLabel.background"
	| "keybindingLabel.foreground"
	| "keybindingLabel.border"
	| "keybindingLabel.bottomBorder"
	// Keyboard shortcut table colors
	| "keybindingTable.headerBackground"
	| "keybindingTable.rowsBackground"
	// Integrated terminal colors
	| "terminal.background"
	| "terminal.border"
	| "terminal.foreground"
	| "terminal.ansiBlack"
	| "terminal.ansiBlue"
	| "terminal.ansiBrightBlack"
	| "terminal.ansiBrightBlue"
	| "terminal.ansiBrightCyan"
	| "terminal.ansiBrightGreen"
	| "terminal.ansiBrightMagenta"
	| "terminal.ansiBrightRed"
	| "terminal.ansiBrightWhite"
	| "terminal.ansiBrightYellow"
	| "terminal.ansiCyan"
	| "terminal.ansiGreen"
	| "terminal.ansiMagenta"
	| "terminal.ansiRed"
	| "terminal.ansiWhite"
	| "terminal.ansiYellow"
	| "terminal.selectionBackground"
	| "terminal.selectionForeground"
	| "terminal.inactiveSelectionBackground"
	| "terminal.findMatchBackground"
	| "terminal.findMatchBorder"
	| "terminal.findMatchHighlightBackground"
	| "terminal.findMatchHighlightBorder"
	| "terminal.hoverHighlightBackground"
	| "terminalCursor.background"
	| "terminalCursor.foreground"
	| "terminal.dropBackground"
	| "terminal.tab.activeBorder"
	| "terminalCommandDecoration.defaultBackground"
	| "terminalCommandDecoration.successBackground"
	| "terminalCommandDecoration.errorBackground"
	| "terminalOverviewRuler.cursorForeground"
	| "terminalOverviewRuler.findMatchForeground"
	// Debug colors
	| "debugToolBar.background"
	| "debugToolBar.border"
	| "editor.stackFrameHighlightBackground"
	| "editor.focusedStackFrameHighlightBackground"
	| "editor.inlineValuesForeground"
	| "editor.inlineValuesBackground"
	| "debugView.exceptionLabelForeground"
	| "debugView.exceptionLabelBackground"
	| "debugView.stateLabelForeground"
	| "debugView.stateLabelBackground"
	| "debugView.valueChangedHighlight"
	| "debugTokenExpression.name"
	| "debugTokenExpression.value"
	| "debugTokenExpression.string"
	| "debugTokenExpression.boolean"
	| "debugTokenExpression.number"
	| "debugTokenExpression.error"
	// Testing colors
	| "testing.iconFailed"
	| "testing.iconErrored"
	| "testing.iconPassed"
	| "testing.runAction"
	| "testing.iconQueued"
	| "testing.iconUnset"
	| "testing.iconSkipped"
	| "testing.peekBorder"
	| "testing.peekHeaderBackground"
	| "testing.message.error.decorationForeground"
	| "testing.message.error.lineBackground"
	| "testing.message.info.decorationForeground"
	| "testing.message.info.lineBackground"
	// Welcome page colors
	| "welcomePage.background"
	| "welcomePage.progress.background"
	| "welcomePage.progress.foreground"
	| "welcomePage.tileBackground"
	| "welcomePage.tileHoverBackground"
	| "welcomePage.tileBorder"
	| "walkThrough.embeddedEditorBackground"
	| "walkthrough.stepTitle.foreground"
	// Source control colors
	| "scm.providerBorder"
	// Git colors
	| "gitDecoration.addedResourceForeground"
	| "gitDecoration.modifiedResourceForeground"
	| "gitDecoration.deletedResourceForeground"
	| "gitDecoration.renamedResourceForeground"
	| "gitDecoration.stageModifiedResourceForeground"
	| "gitDecoration.stageDeletedResourceForeground"
	| "gitDecoration.untrackedResourceForeground"
	| "gitDecoration.ignoredResourceForeground"
	| "gitDecoration.conflictingResourceForeground"
	| "gitDecoration.submoduleResourceForeground"
	// Settings editor colors
	| "settings.headerForeground"
	| "settings.modifiedItemIndicator"
	| "settings.dropdownBackground"
	| "settings.dropdownForeground"
	| "settings.dropdownBorder"
	| "settings.dropdownListBorder"
	| "settings.checkboxBackground"
	| "settings.checkboxForeground"
	| "settings.checkboxBorder"
	| "settings.rowHoverBackground"
	| "settings.textInputBackground"
	| "settings.textInputForeground"
	| "settings.textInputBorder"
	| "settings.numberInputBackground"
	| "settings.numberInputForeground"
	| "settings.numberInputBorder"
	| "settings.focusedRowBackground"
	| "settings.focusedRowBorder"
	| "settings.headerBorder"
	| "settings.sashBorder"
	| "settings.settingsHeaderHoverForeground"
	// Breadcrumbs colors
	| "breadcrumb.foreground"
	| "breadcrumb.background"
	| "breadcrumb.focusForeground"
	| "breadcrumb.activeSelectionForeground"
	| "breadcrumbPicker.background"
	// Snippets colors
	| "editor.snippetTabstopHighlightBackground"
	| "editor.snippetTabstopHighlightBorder"
	| "editor.snippetFinalTabstopHighlightBackground"
	| "editor.snippetFinalTabstopHighlightBorder"
	// Symbol icon colors
	| "symbolIcon.arrayForeground"
	| "symbolIcon.booleanForeground"
	| "symbolIcon.classForeground"
	| "symbolIcon.colorForeground"
	| "symbolIcon.constantForeground"
	| "symbolIcon.constructorForeground"
	| "symbolIcon.enumeratorForeground"
	| "symbolIcon.enumeratorMemberForeground"
	| "symbolIcon.eventForeground"
	| "symbolIcon.fieldForeground"
	| "symbolIcon.fileForeground"
	| "symbolIcon.folderForeground"
	| "symbolIcon.functionForeground"
	| "symbolIcon.interfaceForeground"
	| "symbolIcon.keyForeground"
	| "symbolIcon.keywordForeground"
	| "symbolIcon.methodForeground"
	| "symbolIcon.moduleForeground"
	| "symbolIcon.namespaceForeground"
	| "symbolIcon.nullForeground"
	| "symbolIcon.numberForeground"
	| "symbolIcon.objectForeground"
	| "symbolIcon.operatorForeground"
	| "symbolIcon.packageForeground"
	| "symbolIcon.propertyForeground"
	| "symbolIcon.referenceForeground"
	| "symbolIcon.snippetForeground"
	| "symbolIcon.stringForeground"
	| "symbolIcon.structForeground"
	| "symbolIcon.textForeground"
	| "symbolIcon.typeParameterForeground"
	| "symbolIcon.unitForeground"
	| "symbolIcon.variableForeground"
	// Debug icon colors
	| "debugIcon.breakpointForeground"
	| "debugIcon.breakpointDisabledForeground"
	| "debugIcon.breakpointUnverifiedForeground"
	| "debugIcon.breakpointCurrentStackframeForeground"
	| "debugIcon.breakpointStackframeForeground"
	| "debugIcon.startForeground"
	| "debugIcon.pauseForeground"
	| "debugIcon.stopForeground"
	| "debugIcon.disconnectForeground"
	| "debugIcon.restartForeground"
	| "debugIcon.stepOverForeground"
	| "debugIcon.stepIntoForeground"
	| "debugIcon.stepOutForeground"
	| "debugIcon.continueForeground"
	| "debugIcon.stepBackForeground"
	| "debugConsole.infoForeground"
	| "debugConsole.warningForeground"
	| "debugConsole.errorForeground"
	| "debugConsole.sourceForeground"
	| "debugConsoleInputIcon.foreground"
	// Notebook colors
	| "notebook.editorBackground"
	| "notebook.cellBorderColor"
	| "notebook.cellHoverBackground"
	| "notebook.cellInsertionIndicator"
	| "notebook.cellStatusBarItemHoverBackground"
	| "notebook.cellToolbarSeparator"
	| "notebook.cellEditorBackground"
	| "notebook.focusedCellBackground"
	| "notebook.focusedCellBorder"
	| "notebook.focusedEditorBorder"
	| "notebook.inactiveFocusedCellBorder"
	| "notebook.inactiveSelectedCellBorder"
	| "notebook.outputContainerBackgroundColor"
	| "notebook.outputContainerBorderColor"
	| "notebook.selectedCellBackground"
	| "notebook.selectedCellBorder"
	| "notebook.symbolHighlightBackground"
	| "notebookScrollbarSlider.activeBackground"
	| "notebookScrollbarSlider.background"
	| "notebookScrollbarSlider.hoverBackground"
	| "notebookStatusErrorIcon.foreground"
	| "notebookStatusRunningIcon.foreground"
	| "notebookStatusSuccessIcon.foreground"
	| "notebookEditorOverviewRuler.runningCellForeground"
	// Chart colors
	| "charts.foreground"
	| "charts.lines"
	| "charts.red"
	| "charts.blue"
	| "charts.yellow"
	| "charts.orange"
	| "charts.green"
	| "charts.purple"
	// Ports colors
	| "ports.iconRunningProcessForeground"
	// Comments view colors
	| "commentsView.resolvedIcon"
	| "commentsView.unresolvedIcon";

/**
 * Color settings for syntax highlighting tokens.
 */
export interface TokenColor {
	name?: string;
	scope: string | Array<string>;
	settings: {
		background?: chroma.Color;
		foreground?: chroma.Color;
		fontStyle?: string;
		content?: string;
	};
}

/**
 * Color settings for semantic highlighting.
 */
export type SemanticTokenColors = {
	[T in SemanticTokenSelector]?: chroma.Color;
};

// Note: Non-exhaustive list
// Reference: https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide
type SemanticTokenSelector =
	| `${"*" | SemanticTokenType}`
	| `${"*" | SemanticTokenType}.${SemanticTokenModifier}`
	| `${"*" | SemanticTokenType}:${SemanticTokenLanguage}`
	| `${"*" | SemanticTokenType}.${SemanticTokenModifier}:${SemanticTokenLanguage}`;

type SemanticTokenType =
	| "namespace" // For identifiers that declare or reference a namespace, module, or package
	| "class" // For identifiers that declare or reference a class type
	| "enum" // For identifiers that declare or reference an enumeration type
	| "interface" // For identifiers that declare or reference an interface type
	| "struct" // For identifiers that declare or reference a struct type
	| "typeParameter" // For identifiers that declare or reference a type parameter
	| "type" // For identifiers that declare or reference a type that is not covered above
	| "parameter" // For identifiers that declare or reference a function or method parameters
	| "variable" // For identifiers that declare or reference a local or global variable
	| "property" // For identifiers that declare or reference a member property, member field, or member variable
	| "enumMember" // For identifiers that declare or reference an enumeration property, constant, or member
	| "decorator" // For identifiers that declare or reference decorators and annotations
	| "event" // For identifiers that declare an event property
	| "function" // For identifiers that declare a function
	| "method" // For identifiers that declare a member function or method
	| "macro" // For identifiers that declare a macro
	| "label" // For identifiers that declare a label
	| "comment" // For tokens that represent a comment
	| "string" // For tokens that represent a string literal
	| "keyword" // For tokens that represent a language keyword
	| "number" // For tokens that represent a number literal
	| "regexp" // For tokens that represent a regular expression literal
	| "operator"; // For tokens that represent an operator

type SemanticTokenModifier =
	| "declaration" // For declarations of symbols
	| "definition" // For definitions of symbols, for example, in header files
	| "readonly" // For readonly variables and member fields (constants)
	| "static" // For class members (static members)
	| "deprecated" // For symbols that should no longer be used
	| "abstract" // For types and member functions that are abstract
	| "async" // For functions that are marked async
	| "modification" // For variable references where the variable is assigned to
	| "documentation" // For occurrences of symbols in documentation
	| "defaultLibrary"; // For symbols that are part of the standard library

type SemanticTokenLanguage = "javascript" | "typescript" | "python" | "go" | "java";
